# Generated by Django 6.0.2 on 2026-02-08 04:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('images', models.JSONField(default=list)),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', '-display_order'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('student_photo', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('photo_verified', models.BooleanField(default=False)),
                ('photo_hash', models.CharField(blank=True, help_text='Duplicate detection', max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('age_at_submission', models.PositiveIntegerField(editable=False)),
                ('phone', models.CharField(max_length=20)),
                ('phone_country_code', models.CharField(default='+91', max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('address_house_name', models.CharField(max_length=200)),
                ('address_place', models.CharField(max_length=200)),
                ('address_post_office', models.CharField(max_length=200)),
                ('address_pin_code', models.CharField(max_length=10)),
                ('address_state', models.CharField(max_length=100)),
                ('address_district', models.CharField(max_length=100)),
                ('madrassa_name', models.CharField(blank=True, max_length=200)),
                ('class_stopped', models.CharField(blank=True, max_length=100)),
                ('school_college', models.CharField(blank=True, max_length=200)),
                ('standard', models.CharField(blank=True, max_length=100)),
                ('languages_known', models.JSONField(default=list)),
                ('languages_other', models.CharField(blank=True, max_length=200)),
                ('academic_data', models.JSONField(blank=True, default=dict)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relation', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_phone_country_code', models.CharField(default='+91', max_length=5)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_occupation', models.CharField(blank=True, max_length=200)),
                ('achievements_file', models.FileField(blank=True, null=True, upload_to='achievements/')),
                ('achievements_verified', models.BooleanField(default=False)),
                ('completed_steps', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('draft_saved_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_per_step', models.JSONField(default=dict)),
                ('drop_off_step', models.PositiveIntegerField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('content_blocks', models.JSONField(default=list, help_text='[{"type": "text", "order": 1, "data": {...}}, {"type": "image", "order": 2, "data": {...}}]')),
                ('visible_from', models.DateTimeField(blank=True, null=True)),
                ('visible_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.TextField(blank=True)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('date_hidden', models.DateField(blank=True, help_text='Date stored but hidden from UI', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('min_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('admission_created', 'Admission Created'), ('step_completed', 'Step Completed'), ('submitted', 'Submitted'), ('state_changed', 'State Changed'), ('file_uploaded', 'File Uploaded'), ('admin_action', 'Admin Action'), ('draft_saved', 'Draft Saved')], max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.admission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionStateLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_state', models.CharField(blank=True, max_length=20)),
                ('new_state', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(blank=True, help_text='User or system', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.admission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('time_spent', 'Time Spent'), ('drop_off', 'Drop Off'), ('validation_failed', 'Validation Failed'), ('program_demand', 'Program Demand'), ('conversion', 'Conversion')], max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.admission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_visible_to_staff', models.BooleanField(default=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.admission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('tagged_programs', models.JSONField(default=list, help_text='Program slugs of interest')),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('program_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='core.program'),
        ),
        migrations.CreateModel(
            name='ProgramField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.PositiveIntegerField(help_text='Form step this field belongs to')),
                ('field_key', models.SlugField(help_text="Unique key for this field (e.g., 'arabic_fluent')")),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('multiselect', 'Multi-Select'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('file', 'File Upload'), ('phone', 'Phone Number'), ('email', 'Email'), ('number', 'Number')], max_length=20)),
                ('placeholder', models.TextField(blank=True)),
                ('help_text', models.TextField(blank=True)),
                ('required', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('conditional', 'Conditional')], default='optional', max_length=20)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('show_condition', models.JSONField(blank=True, default=dict, help_text='{"field": "other_field", "value": "specific_value"}')),
                ('choices', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.program')),
            ],
            options={
                'ordering': ['program', 'step', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['state', 'program'], name='core_admiss_state_a677e3_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['created_at'], name='core_admiss_created_0c4707_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['submitted_at'], name='core_admiss_submitt_6a4c5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programfield',
            unique_together={('program', 'field_key')},
        ),
    ]
