# Generated by Django 6.0.2 on 2026-02-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(upload_to='achievements/', null=True, blank=True),
        ),
    ]
